apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-platform
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "np.labels" . | nindent 4 }}
automountServiceAccountToken: false
