apiVersion: v1
kind: ConfigMap
metadata:
  name: email-service-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "np.labels" . | nindent 4 }}
data:
  NODE_ENV: "production"
  KAFKA_BROKERS: "kafka:9092"
  SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
  KAFKA_GROUP_ID: "email-service-group"
  SMTP_HOST: {{ .Values.smtp.host | quote }}
  SMTP_PORT: {{ .Values.smtp.port | quote }}
  SMTP_FROM: {{ .Values.smtp.from | quote }}
