apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gateway-pdb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "np.labels" . | nindent 4 }}
    {{- include "np.selectorLabels" "gateway" | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "np.selectorLabels" "gateway" | nindent 6 }}
