apiVersion: v1
kind: Service
metadata:
  name: schema-registry
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "np.labels" . | nindent 4 }}
    {{- include "np.selectorLabels" "schema-registry" | nindent 4 }}
spec:
  selector:
    {{- include "np.selectorLabels" "schema-registry" | nindent 4 }}
  ports:
    - name: http
      port: 8081
      targetPort: 8081
