apiVersion: v1
kind: Service
metadata:
  name: mailhog
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "np.labels" . | nindent 4 }}
    {{- include "np.selectorLabels" "mailhog" | nindent 4 }}
spec:
  selector:
    {{- include "np.selectorLabels" "mailhog" | nindent 4 }}
  ports:
    - name: smtp
      port: 1025
      targetPort: 1025
    - name: ui
      port: 8025
      targetPort: 8025
  type: NodePort
