{{- if .Values.kafkaUI.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "np.labels" . | nindent 4 }}
    {{- include "np.selectorLabels" "kafka-ui" | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "np.selectorLabels" "kafka-ui" | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "np.labels" . | nindent 8 }}
        {{- include "np.selectorLabels" "kafka-ui" | nindent 8 }}
    spec:
      serviceAccountName: notification-platform
      containers:
        - name: kafka-ui
          image: {{ .Values.kafkaUI.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DYNAMIC_CONFIG_ENABLED
              value: "true"
            - name: KAFKA_CLUSTERS_0_NAME
              value: "notification-platform"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "kafka:9092"
            - name: KAFKA_CLUSTERS_0_SCHEMAREGISTRY
              value: "http://schema-registry:8081"
          resources:
            {{- toYaml .Values.kafkaUI.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 15
            failureThreshold: 3
{{- end }}
